version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@16
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building Angular app...
      - ng build --configuration development

  post_build:
    commands:
      - echo Copying required files to dist/dockey...
      - cp package.json dist/dockey/
      - cp package-lock.json dist/dockey/
      - cp angular.json dist/dockey/
      - cp tsconfig.json dist/dockey/
      - cp buildspec-test.yml dist/dockey/

artifacts:
  files:
    - '**/*'
  base-directory: dist/dockey
  discard-paths: no
