version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@16
      - npm install

  build:
    commands:
      - echo Building Angular app...
      - ng build --configuration development

  post_build:
    # commands:
    #   - echo Build completed.
    #   - echo Copying buildspec-test.yml into dist...
    #   - cp buildspec-test.yml dist/dockey/
    # post_build:
    commands:
      - echo Copying required files to dist/dockey
      - cp package.json dist/dockey/
      - cp package-lock.json dist/dockey/
      - cp buildspec-test.yml dist/dockey/


artifacts:
  files:
    - '**/*'
  base-directory: dist/dockey
  discard-paths: no
